# -*- coding: utf-8 -*-
"""InfRecFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pI2BeM_oNIAL-S3Tkz-C2Nj3mdVkouby

Εισήγαγα την βιβλιοθήκη NLTK για την επεξεργασία γλώσας και για την λήψη του Reuters , για tokenization,stopwords κ.α. Επιπλέον η βιβλιοθήκη Scikit-learn για την μέθοδο TF-IDF και την ομοιότητα εγγράφων.
"""

import nltk
import re
import numpy as np
import requests
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer
from  sklearn.metrics.pairwise import cosine_similarity
from sklearn.datasets import fetch_20newsgroups

nltk.download ('reuters')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download ('punkt_tab') # Προσθήκη για αποφυγή σφαλμάτων σε νεότερες εκδόσεις
from nltk.corpus import reuters, stopwords
from nltk.stem import PorterStemmer

"""Παρακάτω κάνω troubleshoot την εισαγωγή της βιβλιοθήκης για τον BM250, διότι αντιμετώπησα πολλά error κατά την επίλυση της εργασίας

"""

try:
    from rank_bm25 import BM25Okapi
except ImportError :
    import subprocess
    subprocess.check_call(["pip" , "install", "rank_bm25"] )
    from rank_bm25 import BM25Okapi

print("Περιεχόμενα του συνόλου Reuters : \n")

 #Ανέκτησα τα IDs των αρχείων και τις κατηγορίες.
fileIds =  reuters.fileids()
categories = reuters.categories ()

print(f"Το συνολο δεδομενων Reuters περιεχει {len(fileIds)} εγγραφα ")
print(f"Το συνολο των κατηγοριων ειναι {len(categories)}" )
print(f" Δειγμα κατηγοριων {categories[:5]} ")

"""Βημα 2. Δημιούργησα συνάρτηση για την προεπεξεργασια του κειμένου. Αρχικά, μετέτρεψα όλα τα γράμματα σε πεζά στη συνέχεια αφαιρεσα όλους τους ειδικούς χαρακτήρες  χρησιμοποιώντας κανονικές εκφράσεις. Εφάρμοσα τη διαδικασία του tokenization για να σπάσω το κείμενο σε λίστα λέξεων και χρησιμοποιησα τον Porter Stemmer για να μετατρέψω τις λέξεις στη ρίζα τους. Επέλεξα το stemming αντί για το lemmatization διότι είναι υπολογιστικά πιο γρηγορο και επαρκές για την ανάκτηση πληροφορίας. Τέλος, αφαίρεσα τις stopwords."""

stopWords =  set(stopwords.words('english'))
stemmer = PorterStemmer ()

def preprocessText(text):

    #Μετέτρεψα όλα τα γράμματα σε lowercase για μειωθέι το μέγεθος του
    #λεξιλογιου (μην περιλαμβάνει και Apple και apple)
    text = text.lower()


     # Αφαιρεσα τους ειδικούς χαρακτήρες και κράτησα μόνο τα γράμματα χρησιμοποιώντας regex.
    text = re.sub(r'[^a-z\s]', '', text )

      #Έκανα tokenization
    tokens = nltk.word_tokenize( text )

    #Εφάρμοσα stemming και αφαίρεσα τα stopwords
    cleanedTokens  = [stemmer.stem(t) for t in tokens if t not in stopWords ]

    return cleanedTokens

"""Βημα 3. Σε αυτό το στάδιο προχωρησα στη δημιουργία του ανεστραμμένου ευρετηρίου χρησιμοποιώντας τα εγγραφα του Reuters. Ανέκτησα τα IDs των αρχείων και διετρεξα τα πρώτα 2000 από αυτά για να χτίσω τη δομή δεδομένων. Για κάθε έγγραφο , εφάρμοσα την προεπεξεργασία και αποθήκευσα τις μοναδικες λέξεις σε ένα λεξικό με την δομή dictionary της Python . Κάθε λέξη-κλειδί στο ευρετήριο δείχνει σε μια λίστα με τα IDs των εγγράφων στα οποία εμφανιζεται, επιτρέποντας έτσι την άμεση ανάκτηση. Παράλληλα, κράτησα τα επεξεργασμένα κείμενα σε μια λίστα για να τα χρησιμοποιησω αργότερα."""

print("Δημιουργείται ανεστραμμένο ευρετηριο")

invertedIndex = defaultdict (list)
corpusData = []
docIdsList  = []

#Περιόρισα το πληθος για να μην αργεί η επεξεργασία
for docId in fileIds[:2000]:
    rawText = reuters.raw(docId)
    tokens = preprocessText(rawText)

    uniqueTokens = set(tokens)
    for token in uniqueTokens:
        invertedIndex[token].append(docId)

    #Κρατάω τα δεδομένα σε μορφή string για να τα χρησιμοποιησω αργότερα για τον TfidfVectorizer.
    corpusData.append(" ".join(tokens) )
    docIdsList.append( docId )

allDocumentsSet  = set(docIdsList)

print(f"Η ευρετηριαση ολοκληρωθηκε επιτυχως για {len(docIdsList)} κειμενα ")
print(f"Το ευρετηριο περιεχει {len(invertedIndex)} μοναδικους ορους" )

"""Βήμα 4α. Υλοποίησα τη συνάρτηση για την Boolean αναζήτηση, η οποία επιτρέπει στον χρήστη να εκτελεί ερωτήματα με τους λογικούς τελεστες AND, OR και NOT. Στην περίπτωση του NOT, χρησιμοποίησα τη διαφορά συνόλων για να αφαιρεσω τα έγγραφα που περιέχουν τον όρο από το σύνολο όλων των εγγράφων. Για τους τελεστές AND και OR, εφάρμοσα αντίστοιχα την τομή και την ένωση συνόλων πάνω στις λίστες του ευρετηριου μου."""

#Boolean searchh
def booleanSearch(query, index , allDocs):

  parts  = query.split()

  if len(parts) ==  1 :
        term = stemmer.stem(parts[0])
        return  set(index[term])

  if parts[0] == "NOT":
        term = stemmer.stem(parts[1])
        return  allDocs - set(index[term])

  if len(parts) == 3 :
        term1 = stemmer.stem(parts[0])
        operator = parts[1]
        term2 =  stemmer.stem(parts[2])

        docs1 = set(index[term1])
        docs2 = set(index[term2])

        if operator  == "AND":
            return docs1 & docs2
        elif operator == "OR":
            return  docs1 | docs2

  return set ()

print("Παράδειγμα Boolean Search  : " )


exTerm1 = "greece"
exTerm2 =  "bread"

#AND
resultsAnd = booleanSearch(f"{exTerm1} AND  {exTerm2}", invertedIndex, allDocumentsSet)
print(f" Αποτελεσματα αναζητησης {exTerm1} AND {exTerm2} βρεθηκαν {len(resultsAnd)} εγγραφα" )

# OR
resultsOr = booleanSearch(f"{exTerm1} OR {exTerm2}", invertedIndex, allDocumentsSet)
print(f" Αποτελεσματα αναζητησης {exTerm1} OR {exTerm2} βρεθηκαν {len(resultsOr)} εγγραφα")

#NOT
resultsNot = booleanSearch(f"NOT {exTerm1}", invertedIndex , allDocumentsSet )
print(f" Αποτελεσματα αναζητησης NOT {exTerm1} βρεθηκαν {len(resultsNot)} εγγραφα")

"""Βήμα 4β. Για την κατάταξη των αποτελεσμάτων, επελεξα να υλοποιήσω το Μοντέλο Διανυσματικού Χώρου χρησιμοποιώντας τη μεθοδολογία TF-IDF. Αρχικοποίησα τον vectorizer και μετέτρεψα όλα τα έγγραφα της συλλογής σε διανυσματα, ώστε να δώσω έμφαση τις λέξεις με τη μεγαλύτερη βαρύτητα. Στη συνάρτηση αναζήτησης , μετέτρεψα και το ερώτημα του χρήστη σε διάνυσμα στον ίδιο χώρο και υπολογισα την ομοιότητα συνημιτόνου μεταξύ του ερωτήματος και όλων των εγγράφων. Η ομοιότητα συνημιτόνου επιλέχθηκε ως μετρική διότι δεν επηρεαζεται από το μέγεθος των κειμένων. Τέλος , ταξινόμησα τα αποτελέσματα σε φθίνουσα σειρά για να επιστρεψω τα πιο σχετικά έγγραφα στον χρήστη."""

print("Εκπαιδέυεται το μοντέλο Vector Space Model")
vectorizer = TfidfVectorizer()
tfidfMatrix = vectorizer.fit_transform(corpusData)
print(f"Ο πινακας TFIDF δημιουργηθηκε με διαστασεις {tfidfMatrix.shape}")

def vsmSearch(query, vectorizerModel, matrix, docIds ) :
    queryVec =  vectorizerModel.transform([" ".join(preprocessText(query))])
    cosineSim =  cosine_similarity(queryVec, matrix).flatten()
    relatedDocsIndices =  cosineSim.argsort()[::-1][:10]

    results  = []
    for i in relatedDocsIndices:
        if cosineSim[i]  > 0 :
            results.append( (docIds[i] , cosineSim[i]))
    return  results

"""Ενσωμάτωσα τον αλγόριθμο BM25, ο οποίος θεωρείται μια από τις πιο ισχυρές μεθόδους ανάκτησης πληροφοριας. Προετοίμασα τα δεδομένα μου σε μορφή λίστας από tokens, καθώς αυτό απαιτει η βιβλιοθήκη rank_bm25 για να λειτουργήσει. Στη συνάρτηση αναζήτησης, επεξεργάστηκα το ερώτημα και έβαλα από το μοντέλο να υπολογίσει τα σκορ σχετικότητας για κάθε εγγραφο. Επέλεξα το BM25 διότι βελτιώνει τις αδυναμίες του TF-IDF, λαμβάνοντας υπόψη το μήκος του εγγράφου και την συχνότητα των όρων, προσφέροντας έτσι πιο αξιοπιστα αποτελέσματα."""

print ("Εκπαιδεύεται το μοντέλο BM25")

tokenizedCorpus =  [doc.split() for doc in corpusData]
bm25 = BM25Okapi(tokenizedCorpus)
print( " Το μοντέλο BM25 εκπαιδευτηκε" )

def bm25Search(query, bm25Model, docIds):
    queryTokens = preprocessText(query)
    docScores = bm25Model.get_scores(queryTokens)
    topIndices = np.argsort(docScores)[::-1][:10]
    results = []
    for i in topIndices:
        if docScores[i] > 0 :
            results.append((docIds[i] , docScores[i]) )
    return results

"""Πριν προχωρήσω στην αξιολόγηση με το δεύτερο dataset, έκανα δοκιμή της μηχανής αναζήτησης πάνω στα δεδομένα εκπαίδευσης (Reuters). Χρησιμοποιησα ένα ερώτημα παράδειγμα "hello trade" και ζήτησα από τους αλγορίθμους VSM και BM25 να επιστρέψουν τα 5 κορυφαία έγγραφα. Σκοπός αυτού του βήματος ήταν να επιβεβαιωσω οπτικά ότι οι αλγόριθμοι λειτουργούν σωστά και επιστρέφουν κείμενα που περιέχουν τους όρους αναζήτησης, καθώς και να παρατηρήσω τις διαφορές στα σκορ."""

print( "\n Αποτελέσματα αναζητησης στο Reuters Dataset " )

# Ορίζω ένα ερώτημα παράδειγμα για να δούμε τι επιστρέφουν οι αλγόριθμοι
exQuery = "hello trade"

print(f" Ερώτημα Αναζητησης: '{exQuery}'")

# Αποτελέσματα VSM
print("\n VSM : Πρώτα 3 Αποτελεσματα:")
vsmResultsReuters = vsmSearch(exQuery, vectorizer, tfidfMatrix, docIdsList)

for docId, score in vsmResultsReuters[:3]:
    print(f" DocID: {docId} , Score: {score:.4f}")
    # Ανάκτηση μικρού τμήματος κειμένου για επιβεβαίωση
    content = reuters.raw(docId)[:100].replace('\n', ' ')
    print(f"   Κείμενο: {content}...")

#Αποτελέσματα BM25
print("\n BM25 : Πρώτα 3 Αποτελεσματα:")

bm25ResultsReuters = bm25Search(exQuery, bm25, docIdsList)

for docId, score in bm25ResultsReuters[:3]:
    print(f"DocID: {docId} , Score: {score:.4f}")
    content = reuters.raw(docId)[:100].replace('\n', ' ')
    print(f"   Κείμενο: {content}...")

"""Βήμα 5. Ολοκλήρωσα την εργασία υλοποιώντας τη διαδικασία υπολογισμού των μετρικών αξιολόγησης. Για κάθε ερώτημα , ανακτησα τα αποτελέσματα από τους αλγορίθμους και τα σύγκρινα με την πραγματική κατηγορία των κειμένων. Υπολόγισα την ακρίβεια και την ανάκληση στα πρώτα 20 αποτελέσματα, καθώς και το MAP. Επέλεξα να βάλω το MAP διότι είναι μια πιο έυστοχη μετρική που δίνει έμφαση στους αλγορίθμους που εμφανίζουν τα σωστά αποτελέσματα στις πρωτες θέσεις. Τέλος, τύπωσα τα συγκεντρωτικά αποτελέσματα για να μπορέσω να συγκρινω την απόδοση του VSM με του BM25."""

print("Ξεκιναει η αξιολογηση συστηματος με 20 Newsgroups")

newsgroupsTest = fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes') )
docs20News =  newsgroupsTest.data
labels20News = newsgroupsTest.target
targetNames =  newsgroupsTest.target_names

print( f"Το dataset περιέχει {len(docs20News)} κειμενα" )

cleanCorpus20News = []
docIds20News =  []
trueLabels  = []

#Φίλτραρα τα μικρά κείμενα για να είναι πιό σωστή η αξιολόγιση
for i, text in enumerate(docs20News):
    if len(text) > 50:
        tokens = preprocessText(text)
        if tokens:
            cleanCorpus20News.append(" ".join(tokens))
            docIds20News.append(i)
            trueLabels.append(labels20News[i])

print("Γίνεται επανεκπαίδευση με τα νέα δεδομένα " )

# VSM για 20 Newsgroups
vectorizer20News = TfidfVectorizer ()
tfidfMatrix20News = vectorizer20News.fit_transform( cleanCorpus20News )

# BM25 για 20 Newsgroups
tokenizedCorpus20News = [doc.split() for doc in cleanCorpus20News]
bm2520News = BM25Okapi( tokenizedCorpus20News)

evalQueries  = {
    "space nasa orbit launch moon": "sci.space",
    "baseball game player team score": "rec.sport.baseball",
    "encryption security key algorithm": "sci.crypt",
    "doctor medicine disease health virus": "sci.med",
    "car engine speed wheels gear": "rec.autos"
}


def calculateAp( retrievedIndices , trueLabels, targetLabelId):
  relevantCount = 0
  sumPrecision = 0.0

  for i, idx in enumerate(retrievedIndices ) :
        if trueLabels[idx] == targetLabelId:
            relevantCount += 1
            precisionAtK =  relevantCount / (i + 1 )
            sumPrecision  += precisionAtK

  if relevantCount == 0:
        return 0.0

  return  sumPrecision / relevantCount

"""Ολοκλήρωσα τη διαδικασία αξιολόγησης δημιουργώντας τη συναρτηση evaluateFull, η οποία δέχεται ως όρισμα το όνομα του αλγορίθμου και υπολογίζει τις συνολικές μετρικές απόδοσης. Αρχικά, μηδένισα τους αθροιστές για την ακρίβεια , την ανάκληση και το MAP  και ξεκινησα την επανάληψη για κάθε ερώτημα ελέγχου. Υπολόγισα το average precision για το MAP χρησιμοποιώντας και τα 50 αποτελέσματα, ενώ για την ακρίβεια και την ανάκληση περιορισα τη λίστα στα πρώτα 20 έγγραφα. Σύγκρινα τα έγγραφα με την πραγματική κατηγορία τους (Ground Truth) και αθροισα τα σκορ για να υπολογίσω τους τελικούς μέσους όρους. Τέλος, υπολόγισα το F1 score, που αποτελεί τον αρμονικό μέσο όρο ακρίβειας και ανάκλησης, και εκτυπωσα τα συγκριτικά αποτελέσματα στην οθόνη για να παρατηρήσω ποιος αλγόριθμος απέδωσε καλύτερα."""

def evaluateFull(algorithmName):
    totalPrecision = 0
    totalRecall = 0
    totalMap =  0

    print(f"Αξιολογηση επιδοσης αλγοριθμου {algorithmName} " )

    for queryText, targetCategoryName in evalQueries.items():
        if targetCategoryName not in targetNames: continue
        targetLabelId = targetNames.index( targetCategoryName )

        # Ανακτηση
        if algorithmName ==  "VSM" :
            qVec = vectorizer20News.transform( [" ".join(preprocessText(queryText))])
            sims =  cosine_similarity(qVec, tfidfMatrix20News).flatten()
            topIndices = sims.argsort()[::-1][:50]

        elif algorithmName == "BM25":
            qTokens = preprocessText(queryText )
            scores =  bm2520News.get_scores(qTokens)
            topIndices = np.argsort(scores)[::-1][:50]

        # ΜΑΡ
        ap = calculateAp( topIndices, trueLabels, targetLabelId )
        totalMap += ap

        # Precision και Recall
        top20 = topIndices[:20]
        relevantRetrieved = 0
        for idx in top20:
            if trueLabels[idx]  == targetLabelId:
                relevantRetrieved += 1

        precision = relevantRetrieved / 20
        totalRelevantInDb = trueLabels.count(targetLabelId)

        recall = relevantRetrieved / totalRelevantInDb if totalRelevantInDb > 0 else 0

        totalPrecision += precision
        totalRecall += recall

    avgP = totalPrecision / len(evalQueries)
    avgR =  totalRecall / len(evalQueries)
    mapScore = totalMap / len(evalQueries)

    f1 = 0
    if (avgP + avgR) > 0  :
        f1 = 2 * (avgP * avgR) / (avgP + avgR)

    return avgP , avgR, f1 , mapScore

# Εκτέλεση Αξιολόγησης
pVsm , rVsm, f1Vsm , mapVsm = evaluateFull("VSM")
print(f"Τελικα αποτελεσματα VSM Precision {pVsm:.4f} Recall {rVsm:.4f} F1 {f1Vsm:.4f} MAP {mapVsm:.4f}")

pBm25 , rBm25 , f1Bm25 , mapBm25 = evaluateFull("BM25")
print(f"Τελικα αποτελεσματα BM25 Precision {pBm25:.4f} Recall {rBm25:.4f} F1 {f1Bm25:.4f} MAP {mapBm25:.4f}")